-- Generati automaticamente con www.mockaroo.com
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Chucho', 'Westcott', 7120, 'Lombardia', 'Milano', 43);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Desiree', 'Munkton', 5304, 'Toscana', 'Livorno', 64);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Julietta', 'Asquith', 5308, 'Toscana', 'Firenze', 41);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Cristabel', 'Tieman', 5282, 'Lazio', 'Roma', 83);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Alica', 'Terne', 8508, 'Calabria', 'Reggio Calabria', 14);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Camey', 'Rapson', 205, 'Veneto', 'Padova', 60);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Kerwinn', 'Rupp', 4729, 'Veneto', 'Venezia', 59);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Kendre', 'Radmer', 1467, 'Lazio', 'Roma', 86);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Adelice', 'Please', null, 'Friuli-Venezia Giulia', 'Trieste', 35);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Pat', 'Jovasevic', 133, 'Lazio', 'Roma', 32);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Chaddie', 'Earl', 8050, 'Veneto', 'Padova', 65);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Kali', 'Figgen', 2948, 'Toscana', 'Firenze', 7);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Costa', 'Please', null, 'Veneto', 'Verona', 30);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Cathryn', 'Zanicchi', 1589, 'Veneto', 'Verona', 31);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Mar', 'Gruszecki', 877, 'Lombardia', 'Milano', 26);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Maire', 'Carrigan', 9381, 'Emilia-Romagna', 'Bologna', 56);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Brina', 'Capozzi', 620, 'Lombardia', 'Milano', 80);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Grethel', 'Seywood', 4589, 'Emilia-Romagna', 'Bologna', 12);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Marley', 'Neilands', 5708, 'Lazio', 'Roma', 53);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Jeanie', 'Sisey', 4415, 'Lombardia', 'Milano', 65);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Isac', 'Damarell', null, 'Veneto', 'Verona', 41);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Cordi', 'Sturney', 7002, 'Calabria', 'Reggio Calabria', 24);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('North', 'Giacobbo', 6624, 'Piemonte', 'Torino', 24);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Codi', 'Eller', 9614, 'Lazio', 'Roma', 47);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Esther', 'Adey', 2687, 'Lombardia', 'Milano', 24);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Stefanie', 'Jarrette', 1587, 'Veneto', 'Venezia', 67);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Michaelina', 'Gayton', null, 'Veneto', 'Padova', 82);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Dannye', 'Fortnam', 4046, 'Lombardia', 'Bergamo', 50);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Michel', 'Matyas', 8543, 'Emilia-Romagna', 'Bologna', 55);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Darill', 'Ciccoloi', 9200, 'Friuli-Venezia Giulia', 'Trieste', 33);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Aguste', 'Pragnell', null, 'Emilia-Romagna', 'Bologna', 38);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Moshe', 'Autrie', 9232, 'Toscana', 'Firenze', 44);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Murvyn', 'Gallatly', 4426, 'Piemonte', 'Torino', 66);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Florance', 'Commin', null, 'Emilia-Romagna', 'Villanova', 41);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Codie', 'Starking', 9766, 'Calabria', 'Reggio Calabria', 19);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Adelaide', 'Hornbuckle', 9123, 'Veneto', 'Padova', 61);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Janeva', 'Cowtherd', 9639, 'Veneto', 'Venezia', 79);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Ferrel', 'Martindale', 5819, 'Piemonte', 'Torino', 70);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Milli', 'Vassall', 2676, 'Lombardia', 'Brescia', 67);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Vidovik', 'Eschalotte', 279, 'Toscana', 'Livorno', 13);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Nata', 'Climpson', null, 'Lazio', 'Roma', 65);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Sheilah', 'Blabey', null, 'Toscana', 'Firenze', 40);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Cristian', 'Dugmore', 3679, 'Lazio', 'Roma', 92);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Torey', 'Kears', 8197, 'Emilia-Romagna', 'Villanova', 38);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Giulietta', 'Asser', 5104, 'Veneto', 'Verona', 43);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Paulina', 'Schuchmacher', 3998, 'Lombardia', 'Brescia', 23);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Darbie', 'Town', 2414, 'Calabria', 'Reggio Calabria', 32);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Leslie', 'Deacock', 9420, 'Lazio', 'Roma', 20);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Aindrea', 'D''Adda', 1837, 'Lazio', 'Roma', 69);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Dynah', 'Matskevich', 3026, 'Friuli-Venezia Giulia', 'Trieste', 83);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Retha', 'Kembrey', 1346, 'Emilia-Romagna', 'Bologna', 91);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Domini', 'Barck', 9360, 'Lombardia', 'Bergamo', 73);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Olimpia', 'Brownsmith', 2141, 'Lazio', 'Roma', 46);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Waite', 'Slyman', 4360, 'Veneto', 'Venezia', 12);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Annabelle', 'Lagadu', 86, 'Veneto', 'Mestre', 50);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Carlee', 'Tidder', 8563, 'Piemonte', 'Torino', 4);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Dolli', 'Sheridan', 6616, 'Lazio', 'Roma', 73);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Andros', 'Casse', 1234, 'Veneto', 'Padova', 16);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Freddi', 'Solano', 6070, 'Friuli-Venezia Giulia', 'Trieste', 8);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Hans', 'Fulford', 3960, 'Veneto', 'Venezia', 50);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Delila', 'De Lacey', 3709, 'Veneto', 'Padova', 17);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Boigie', 'Ahren', 4347, 'Friuli-Venezia Giulia', 'Trieste', 42);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Courtney', 'Doxsey', 602, 'Lombardia', 'Milano', 88);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Erastus', 'Claire', 462, 'Emilia-Romagna', 'Bologna', 49);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Karine', 'Posselow', 1290, 'Piemonte', 'Torino', 68);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Shelden', 'O''Bradden', 8942, 'Emilia-Romagna', 'Villanova', 53);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Dorotea', 'Machel', 2719, 'Veneto', 'Verona', 24);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Brice', 'Tourville', 6603, 'Veneto', 'Padova', 39);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Brynna', 'Cunradi', null, 'Friuli-Venezia Giulia', 'Trieste', 54);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Hans', 'Rawling', 1906, 'Lazio', 'Roma', 30);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Hadria', 'Baike', null, 'Friuli-Venezia Giulia', 'Trieste', 41);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Forester', 'Baigent', 2513, 'Toscana', 'Firenze', 89);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Paolo', 'Reignolds', null, 'Lazio', 'Roma', 96);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Fowler', 'Mulrenan', 8131, 'Lazio', 'Roma', 74);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Maddie', 'Alliban', 7261, 'Veneto', 'Padova', 81);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Bambie', 'Ambrogini', 5143, 'Lombardia', 'Milano', 68);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Beret', 'Grent', 1721, 'Toscana', 'Firenze', 2);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Paco', 'Devita', 8356, 'Lazio', 'Roma', 33);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Vincents', 'Lownes', 1687, 'Toscana', 'Livorno', 7);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Farr', 'Konig', null, 'Veneto', 'Mestre', 47);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Byram', 'Ayrs', 2914, 'Lombardia', 'Milano', 23);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Morissa', 'Casiero', 4137, 'Lazio', 'Roma', 99);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Bernice', 'Pratten', 3759, 'Friuli-Venezia Giulia', 'Trieste', 39);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Del', 'Sings', 2926, 'Emilia-Romagna', 'Villanova', 74);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Anastasia', 'Giovannoni', 5520, 'Lombardia', 'Bergamo', 73);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Lindsy', 'Novakovic', 9618, 'Friuli-Venezia Giulia', 'Trieste', 53);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Fredelia', 'Giacopelo', 9938, 'Lombardia', 'Milano', 84);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Timothy', 'Tomlin', 6802, 'Lombardia', 'Milano', 25);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Roana', 'McDuall', 3833, 'Lombardia', 'Milano', 72);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Shayne', 'Franceschino', null, 'Piemonte', 'Torino', 14);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Lynda', 'Atkinson', 3877, 'Piemonte', 'Torino', 54);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Marietta', 'Maslen', 454, 'Lombardia', 'Milano', 93);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Rolfe', 'Vice', 3753, 'Toscana', 'Firenze', 77);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Andria', 'Martinez', 4708, 'Toscana', 'Firenze', 71);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Horacio', 'Karlolczak', 7038, 'Veneto', 'Mestre', 24);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Rycca', 'Reschke', null, 'Toscana', 'Firenze', 88);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Theo', 'Loomis', 765, 'Piemonte', 'Torino', 22);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Klaus', 'Batho', 5845, 'Lazio', 'Roma', 30);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Rhonda', 'Crich', 4859, 'Veneto', 'Padova', 68);
insert into Rappresentante (Nome, Cognome, UltimoFatturato, Regione, Provincia, PercentualeProvvigione) values ('Gabriella', 'MacCague', 4032, 'Lombardia', 'Milano', 100);
